{% set name = "openinference-instrumentation" %}
{% set version = "0.1.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation-{{ version }}.tar.gz
  sha256: f59e02d9b45acc8aab4c11c00f6cc6ff6b63a2487e04741cf145702e85408072

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13
    - opentelemetry-api
    - opentelemetry-sdk
    - openinference-semantic-conventions
    - typing-extensions

test:
  imports:
    - openinference.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: OpenInference instrumentation utilities
  home: https://github.com/Arize-ai/openinference/tree/main/python/openinference-instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikeldking
    - anticorrelator
    - RogerHYang
    - michaelschiff
    - axiomofjoy
