{% set name = "openinference-instrumentation" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation-{{ version }}.tar.gz
  sha256: 91b006a61226e2a30c8ed23a1454aff313306bb6d137e897d4a72403cdd2d548

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - pip
  run:
    - python >=3.8,<3.13
    - opentelemetry-api

test:
  imports:
    - openinference.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenInference instrumentation utilities
  home: https://github.com/Arize-ai/openinference/tree/main/python/openinference-instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikeldking
    - anticorrelator
    - RogerHYang
    - michaelschiff
    - axiomofjoy
