{% set name = "openinference-instrumentation" %}
{% set version = "0.1.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation-{{ version }}.tar.gz
  sha256: 95beaebf8cd2729a4681aaf96a607657c9ed4d4bab6a2fce25e2e1c20850e224

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.13
    - opentelemetry-api
    - opentelemetry-sdk
    - openinference-semantic-conventions
    - typing-extensions

test:
  imports:
    - openinference.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: OpenInference instrumentation utilities
  home: https://github.com/Arize-ai/openinference/tree/main/python/openinference-instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikeldking
    - anticorrelator
    - RogerHYang
    - michaelschiff
    - axiomofjoy
