{% set name = "openinference-instrumentation" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation-{{ version }}.tar.gz
  sha256: c6f47fe6c94386022e706548d3d5b2b1b29396a61acd3ad3358357c6b381e46c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - hatchling
    - pip
  run:
    - python >=3.8,<3.13
    - opentelemetry-api
    - openinference-semantic-conventions
    - typing-extensions

test:
  imports:
    - openinference.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  summary: OpenInference instrumentation utilities
  home: https://github.com/Arize-ai/openinference/tree/main/python/openinference-instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mikeldking
    - anticorrelator
    - RogerHYang
    - michaelschiff
    - axiomofjoy
